TYPO3:
  Flow:
    security:
      authentication:
        providers:
          SingleSignOnProvider:
            provider: 'TYPO3\SingleSignOn\Client\Security\SingleSignOnProvider'
            providerOptions:
              server: DemoServer
            entryPoint: 'TYPO3\SingleSignOn\Client\Security\EntryPoint\SingleSignOnRedirect'
            entryPointOptions:
              server: DemoServer

  SingleSignOn:
    Client:
      client:
        # Identifier of the DemoInstance client
        identifier: ''
        # Key pair UUID of the DemoInstance client
        keyPairUuid: ''

      server:
        DemoServer:
          # Authentication endpoint URI of a SSO server
          endpointUri: ''
          # Public key fingerprint of a SSO server
          publicKeyUuid: ''

      accountMapper:
        typeMapping:
          # Map a user type from the server to one of the instance, more complex scenarios
          # need a specialized account mapper implementation (see GlobalAccountMapperInterface)
          'Acme\DemoServer\Domain\Model\User': 'Acme\DemoInstance\Domain\Model\User'

Acme:
  DemoInstance:
    demoServerUri: http://ssodemoserver.dev/